### ISSUE TITLE
NullPointerException in TrueTypeFontParser.getCmapTable seen on wild PDF's

### ISSUE THREAD

**Issue by ravn** [veraPDF/veraPDF-parser#181]
The following exception (and variants thereof as invoked from elsewhere in the code) is causing VeraPDF to fail processing.    This is with parser-1.0.4.jar artifact downloaded with Maven, running with OpenJDK 8 under Ubuntu 16.10.  At least one of the failing files have been generated with Adobe InDesign CS6 (Windows) and appears to have a full page ad.    I cannot immediately share the failing files in public due to copyright.

```
Caused by: java.lang.NullPointerException
	at org.verapdf.pd.font.truetype.TrueTypeFontParser.getCmapTable(TrueTypeFontParser.java:149)
	at org.verapdf.pd.font.truetype.TrueTypeFontProgram.containsCode(TrueTypeFontProgram.java:84)
	at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getUsedGlyphs(GFOpTextShow.java:163)
	at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getLinkedObjects(GFOpTextShow.java:116)
	at org.verapdf.gf.model.impl.operator.textshow.GFOp_TJ_Big.getLinkedObjects(GFOp_TJ_Big.java:59)
	at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:240)
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:185)
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:136)
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:107)
	... 46 more
```

**Comment by ravn** [comment]
From immediate inspection the `cmapInfos` variable (which is the culprit here) should have triggered a "variable not initialized" warning from the compiler.

**Comment by bdoubrov** [comment]
Fixed in 1.1.8
http://downloads.verapdf.org/gf/verapdf-1.1.8-GF-installer.zip

**Comment by ravn** [comment]
Thank you.  Can you please confirm that the 1.1.8 release corresponds to 1.1.6 of the org.verapdf:validation-model maven artifact which is what we use to pull in the rest.

**Comment by carlwilson** [comment]
Hi, I've just checked the Jenkins fingerprints and that's the case: http://jenkins.openpreservation.org/job/veraPDF-apps-gf-dev/8/fingerprints/

**Comment by ravn** [comment]
It appears that http://downloads.verapdf.org/gf/verapdf-1.1.8-GF-installer.zip is not uploaded yet (it is not on http://downloads.verapdf.org/gf/).  It appears that it is available from http://downloads.verapdf.org/dev/ as well as a 1.1.9 version.  How should I approach this?

**Comment by carlwilson** [comment]
Hi @ravn our greenfield build and delivery has grown a little organically, we'd like to offer all of the development builds from the `dev` area of the web-site as this is clearer. The versions available in http://downloads.verapdf.org/dev/ are the correct ones, we'll only be putting release builds of the GF software into http://downloads.verapdf.org/gf/ (so 1.2 next). Is that clear / OK for now? The links are documented here: http://docs.verapdf.org/install/

**Comment by ravn** [comment]
Yes, this is much clearer.  I'm fine with reorganization and new rules, but not very good at guessing these new rules.  I am running new tests to see if the 1.1.8 release is stable enough for us until 1.2 is available.  Thanks.
