### ISSUE TITLE
NullPointerException in TrueTypeFontProgram.getWidth() in PDF files seen in the wild.

### ISSUE THREAD

**Issue by ravn** [veraPDF/veraPDF-parser#182]
In maven artifact 

```
       <dependency>
            <groupId>org.verapdf</groupId>
            <artifactId>validation-model</artifactId>
            <version>${verapdf.validation.version}</version>
        </dependency>

```
where 
`        <verapdf.validation.version>1.1.6</verapdf.validation.version>
`
we have found a single-page pdf which triggers the following exception.  The page in question contains a full page crossword puzzle and opens fine in Evince under Ubuntu 16.10.

WARNING: Exception caught when validaing item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:109)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:86)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:84)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:84)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:84)
        at org.verapdf.processor.BatchFileProcessor.processContainer(BatchFileProcessor.java:61)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:93)
        at org.verapdf.cli.VeraPdfCliProcessor.processBatch(VeraPdfCliProcessor.java:182)
        at org.verapdf.cli.VeraPdfCliProcessor.processDir(VeraPdfCliProcessor.java:145)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:124)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:100)
Caused by: java.lang.NullPointerException
        at org.verapdf.pd.font.truetype.TrueTypeFontProgram.getWidth(TrueTypeFontProgram.java:136)
        at org.verapdf.pd.font.truetype.TrueTypeFontProgram.getWidth(TrueTypeFontProgram.java:120)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.checkWidths(GFOpTextShow.java:272)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getUsedGlyphs(GFOpTextShow.java:171)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getLinkedObjects(GFOpTextShow.java:118)
        at org.verapdf.gf.model.impl.operator.textshow.GFOp_TJ_Big.getLinkedObjects(GFOp_TJ_Big.java:59)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:240)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:185)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:136)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:107)
        ... 13 more

**Comment by bdoubrov** [comment]
Hi @ravn, I wonder if it is possible to attach the problematic PDF or send it directly to me (boris.doubrov@duallab.com) by email?

**Comment by ravn** [comment]
I have mailed it to you directly.

**Comment by bdoubrov** [comment]
The fix included in the latest dev build: http://downloads.verapdf.org/dev/verapdf-1.1.12-GF-installer.zip

Or use:
`<verapdf.validation.version>1.1.11</verapdf.validation.version>`
for the maven build.
