### ISSUE TITLE
Crash in org.verapdf.pd.font.type1.Type1FontProgram.processToken(Type1FontProgram.java:153)

### ISSUE THREAD

**Issue by thfi** [veraPDF/veraPDF-parser#219]
I have created a very small PDF file using pdflatex and using the [`pdfx` package](https://www.ctan.org/pkg/pdfx) in order to generate a PDF/A-1b-compliant file. Checking this file crashes VeraPDF, supposely during font parsing:
```
<?xml version="1.0" encoding="utf-8"?>
<report>
  <buildInformation>
    <releaseDetails id="core" version="1.4.1" buildDate="2017-04-20T02:01:00+02:00"></releaseDetails>
    <releaseDetails id="validation-model" version="1.4.4" buildDate="2017-04-20T03:30:00+02:00"></releaseDetails>
    <releaseDetails id="gui" version="1.4.0" buildDate="2017-04-20T18:39:00+02:00"></releaseDetails>
  </buildInformation>
  <jobsMay 15, 2017 11:13:15 AM org.verapdf.processor.ProcessorImpl validate
WARNING: Exception caught when validaing item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:109)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.cli.VeraPdfCliProcessor.processFiles(VeraPdfCliProcessor.java:155)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:129)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:99)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -115
        at org.verapdf.pd.font.type1.Type1FontProgram.processToken(Type1FontProgram.java:153)
        at org.verapdf.pd.font.type1.Type1FontProgram.parseFont(Type1FontProgram.java:95)
        at org.verapdf.gf.model.impl.pd.font.GFPDType1Font.<init>(GFPDType1Font.java:63)
        at org.verapdf.gf.model.factory.fonts.FontFactory.parseFont(FontFactory.java:69)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.parseFont(GFOpTextShow.java:227)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getVeraModelFont(GFOpTextShow.java:137)
        at org.verapdf.gf.model.factory.operators.OperatorParser.addFontAndColorSpace(OperatorParser.java:491)
        at org.verapdf.gf.model.factory.operators.OperatorParser.parseOperator(OperatorParser.java:244)
        at org.verapdf.gf.model.factory.operators.OperatorFactory.operatorsFromTokens(OperatorFactory.java:115)
        at org.verapdf.gf.model.impl.pd.GFPDContentStream.parseOperators(GFPDContentStream.java:89)
        at org.verapdf.gf.model.impl.pd.GFPDContentStream.isContainsTransparency(GFPDContentStream.java:113)
        at org.verapdf.gf.model.impl.pd.GFPDPage.parseContentStream(GFPDPage.java:199)
        at org.verapdf.gf.model.impl.pd.GFPDPage.getContentStream(GFPDPage.java:188)
        at org.verapdf.gf.model.impl.pd.GFPDPage.getLinkedObjects(GFPDPage.java:115)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:240)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:185)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:136)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:107)
        ... 8 more

>
    <job>
      <item size="22630">
        <name>/tmp/verapdfcrash.pdf</name>
      </item>
      <taskResult type="VALIDATE" isExecuted="true" isSuccess="false">
        <duration start="1494839594702" finish="1494839595076">00:00:00:374</duration>
        <exceptionMessage>Exception: Caught unexpected runtime exception during validation caused by exception: -115</exceptionMessage>
      </taskResult>
      <duration start="1494839594702" finish="1494839595076">00:00:00:374</duration>
    </job>
  </jobs>
  <batchSummary totalJobs="1" failedToParse="0" encrypted="0">
    <validationReports compliant="0" nonCompliant="0" failedJobs="1">1</validationReports>
    <featureReports failedJobs="0">0</featureReports>
    <repairReports failedJobs="0">0</repairReports>
    <duration start="1494839594590" finish="1494839595092">00:00:00:502</duration>
  </batchSummary>
</report>
```

Attached is the LaTeX source code, the xmpdata file, the log output generated by pdflatex, and the generated PDF file.
[verapdfcrash.zip](https://github.com/veraPDF/veraPDF-parser/files/1000635/verapdfcrash.zip)

**Comment by shem-sergey** [comment]
Hello!
This issue is a copy of issue https://github.com/veraPDF/veraPDF-library/issues/744 and it was fixed in veraPDF/veraPDF-parser#220.
Thank you for reporting this error!
