### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-parser#226]
veraPDF 1.4.7 reports an ArrayIndexOutOfBounds exception when validating this document:
[ArrayIndexOutOfBoundsException-1.pdf](https://github.com/veraPDF/veraPDF-parser/files/1044083/ArrayIndexOutOfBoundsException-1.pdf)

org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:109)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.cli.VeraPdfCliProcessor.processFiles(VeraPdfCliProcessor.java:157)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:131)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:99)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 603
        at org.verapdf.pd.font.cff.CFFType1FontProgram.getGlyphName(CFFType1FontProgram.java:230)
        at org.verapdf.pd.font.cff.CFFType1FontProgram.containsCode(CFFType1FontProgram.java:285)
        at org.verapdf.pd.font.cff.CFFFontProgram.containsCode(CFFFontProgram.java:152)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getUsedGlyphs(GFOpTextShow.java:170)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getLinkedObjects(GFOpTextShow.java:118)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpStringTextShow.getLinkedObjects(GFOpStringTextShow.java:55)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:240)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:185)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:136)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:107)
        ... 8 more

**Comment by a20god** [comment]
veraPDF seems to try to use the font's Encoding data, but that font is indexed by GIDs.
